//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz01.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PV_Quiz01Entities : DbContext
    {
        public PV_Quiz01Entities()
            : base("name=PV_Quiz01Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<spConsultarTodasLasPeliculas_Result> spConsultarTodasLasPeliculas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarTodasLasPeliculas_Result>("spConsultarTodasLasPeliculas");
        }
    
        public virtual int spCrearPelicula(string nombre, Nullable<int> anhoEstreno, string genero, Nullable<System.DateTime> fechaCreacion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var anhoEstrenoParameter = anhoEstreno.HasValue ?
                new ObjectParameter("anhoEstreno", anhoEstreno) :
                new ObjectParameter("anhoEstreno", typeof(int));
    
            var generoParameter = genero != null ?
                new ObjectParameter("genero", genero) :
                new ObjectParameter("genero", typeof(string));
    
            var fechaCreacionParameter = fechaCreacion.HasValue ?
                new ObjectParameter("fechaCreacion", fechaCreacion) :
                new ObjectParameter("fechaCreacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCrearPelicula", nombreParameter, anhoEstrenoParameter, generoParameter, fechaCreacionParameter);
        }
    }
}
